### ISSUE TITLE
Custom Widget Configuration Button Missing – Unable to Edit or Recover Code

### ISSUE THREAD

**Issue by agrippaharfleur** [gristlabs/grist-widget#146]
hi @berhalak, 

I'm running into an issue with my custom widget builders. For some (most) of them, at some point, the "open configuration" button disappears, and I can't edit my widget or recover my code anymore 😢.

Have you heard of this before? Any chance you might know how to fix it?

<img width="262" alt="Capture d’écran 2024-12-04 à 11 18 11" src="https://github.com/user-attachments/assets/edb073a9-ca1d-4932-a595-42544dab7e76">

<img width="257" alt="Capture d’écran 2024-12-04 à 11 17 53" src="https://github.com/user-attachments/assets/d3b3a19d-8b2b-4d5a-8cb2-f1fa344962d4">

**Comment by agrippaharfleur** [comment]
Hi @berhalak 

Just checking in on the issue, have there been any updates since? 🤞

**Comment by berhalak** [comment]
Hi @agrippaharfleur,

Do you have a reliable way to reproduce it? I tried for an hour or two last week, but couldn't do it.

**Comment by agrippaharfleur** [comment]
Hi @berhalak 

I have no idea, but here you can access my document with exemples : https://grist.numerique.gouv.fr/o/docs/mEHQDmKpQtrp/103-TABULA-public-copy?utm_id=share-doc

(it's only fictional data and a copy doc)

**Comment by berhalak** [comment]
It is fixed now, how that works for you.
