### ISSUE TITLE
How to calculate properly - Custom Invoice

### ISSUE THREAD

**Issue by nittygrittytechy** [gristlabs/grist-widget#23]
Hello,

I recently added your updated code for the invoice.js. You provided this:
` row.Total = row.Subtotal + (row.Taxes || 0) - (row.Deduction || 0);`

However, I need for this to multiply a fee charge. Here is the code I have, but it is not appearing correctly on the invoice.
`   addDemo(row); 
      if (!row.Subtotal && !row.Total && row.Items && Array.isArray(row.Items)) {
      try {
        row.Subtotal = row.Items.reduce((a, b) => a + b.Rate * b.Qty, 0);
        row.Total = row.Subtotal;
             row.Total = row.Subtotal * (row.Taxes || 0) - (row.Deduction || 0);
      } catch (e) {
        console.error(e);
      } 
  }`
![image](https://user-images.githubusercontent.com/72896149/164010905-e3804877-b31f-4848-a6bf-fafb4bc68d0d.png)

Can you please advise me how to calculate the row.Taxes (Fees) and then subtract the row.Deduction (Trust Fund).

Thank you

**Comment by paulfitz** [comment]
@nittygrittytechy your formula is currently taking 1500, multiplying it by 0.01 to get 15, and then subtracting 5 to get 10.
If I understand what you want fees to do, you may want to take 1500, multiply it by 1.01 to get 1515, and then subtract 5 to get 1510? If that is right, you can replace `(row.Taxes || 0)` with `(1 + (row.Taxes || 0))` to get that behavior I think.

**Comment by nittygrittytechy** [comment]
Oh!!!!, yes that is what I need. Okay let me try that, thank you so much :).

**Comment by nittygrittytechy** [comment]
Perfect, that woked. 
![image](https://user-images.githubusercontent.com/72896149/164051199-06d65d22-7758-4e2e-ae7b-693ccbc08939.png)

May I ask one more question.

How do I change the appearance to be a $ sign to a % sign on the Fees column?

Thank you

**Comment by paulfitz** [comment]
The currency formatting is set up here:
https://github.com/gristlabs/grist-widget/blob/81eec9455a9240a6d1c4dca8a2bd4a93d1b8a689/invoices/invoice.js#L71-L81
For percentage formatting you could copy these lines to make a percentage filter, perhaps like this (not tested though so could have bugs):
```js
Vue.filter('percentage', formatNumberAsPercentage)
function formatNumberAsPercentage(value) {
  if (!value) { return '—'; }
  const result = Number(value).toLocaleString('en', {
    style: 'percent',
  })
  if (result.includes('NaN')) {
    return value;
  }
  return result;
}
```
Then, in `index.html`, tweak this line: https://github.com/gristlabs/grist-widget/blob/81eec9455a9240a6d1c4dca8a2bd4a93d1b8a689/invoices/index.html#L140 to say `percentage` instead of `currency`.

**Comment by nittygrittytechy** [comment]
Hello,

I have one more thing for the custom invoice. Is there a way to add a $0.00 instead of a line under the words TRUST FUND and FEES?
![image](https://user-images.githubusercontent.com/72896149/165347909-7de74498-b683-4ae5-b68d-658ac541c74e.png)

Also, when I add a TRUST FUND amount and it zero's out the total, there is a line there as well. Can we make that show $0.00 due instead of a line?
![image](https://user-images.githubusercontent.com/72896149/165348032-65fe4f37-a237-4b71-ade1-38c78d5d3322.png)

Thank you :)

**Comment by paulfitz** [comment]
Hi @nittygrittytechy, in places where you see `if (!value) { return '—'; }`, you could perhaps do `value = value || 0` instead, or just change `!value` to be `value === null || value === undefined`.

**Comment by nittygrittytechy** [comment]
Okay great, this worked. Thank you so much!!!!!

Quick question, do I need the second part of the code {return '-';}
![image](https://user-images.githubusercontent.com/72896149/165522434-bd3c0347-486d-4c6a-a934-67d981be0916.png)

**Comment by paulfitz** [comment]
I think for your exact situation you could remove that line entirely, but it seems reasonable to handle the case of nothing being filled in at all.

**Comment by nittygrittytechy** [comment]
Okay then I will just leave it, thank you :)
