### ISSUE TITLE
Adding Merge Tags to URL - Make Payment

### ISSUE THREAD

**Issue by nittygrittytechy** [gristlabs/grist-widget#25]
Hello,

I have no idea if this is possible, but really hoping so.

Within the custom invoice (index.html), I created a pay now button. Within the URL it looks like this
` <div class="footer">
          <p class="PayInfo">Please click on the button below to make your payment today.</p>
          <div class="PayBTN"><a href="https://uslawpros.com/client-payments/?invoice={{ invoice.Number }}&client={{ business }}"><button>Pay Now</button></a></div>
          <div class="thanks">
            Thank you!
          </div>
        </div>`
![image](https://user-images.githubusercontent.com/72896149/165578242-8dd1c9b7-b384-4045-9822-2b345c7f26b9.png)

I call these merge tags, and it pulls in the content. However, it is not pulling in the content.
This is the results
![image](https://user-images.githubusercontent.com/72896149/165576889-643f3f53-9a50-4d5a-8caa-5910000024ae.png)

Is there a way to pull in the data into this URL, so when the client clicks on the button, it automatically fills in the information for them?

Thank you

P.S. I just noticed the Invoice number is missing.

**Comment by paulfitz** [comment]
For this widget we used the Vue.js framework which you can learn about here https://vuejs.org/ including how to use its templating support. I'm not personally very familiar with it. I don't think you can use the `{{...}}` syntax directly in attributes, I think you want something like `<a v-bind:href="an expression">...</a>`, where your expression would translate to perhaps `'https://uslawpros.com/client-payments/?invoice=' + invoice.Number + '&client=' + business` if I understand the setup correctly.

**Comment by nittygrittytechy** [comment]
Well, I added the code but now the invoice does not show at all, hmm.
` <div class="footer">
          <p class="PayInfo">Please click on the button below to make your payment today.</p>
          <div class="PayBTN"><a v-bind:href="https://uslawpros.com/client-payments/?invoice=' + invoice.Number + '&client=' + business"><button>Pay Now</button></a></div>
          <div class="thanks">
            Thank you!
          </div>
        </div>`
![image](https://user-images.githubusercontent.com/72896149/165638548-e63d2091-b242-41a6-8a01-fd391193ddf8.png)

**Comment by dsagal** [comment]
I spot a missing single quote right after the double-quote here: `<a v-bind:href="https://uslawpros.com/client-payments/?invoice=' +`. Could that be the problem? If not, there may be errors in the [browser console](https://balsamiq.com/support/faqs/browserconsole/) that guide you to the issue.

**Comment by nittygrittytechy** [comment]
Well, it didn't work. I got a different error. I am not familiar with Vue.js. 

Thank you for trying to help me :)

**Comment by paulfitz** [comment]
Hi @nittygrittytechy, I made a quick test here: https://docs.getgrist.com/2QgqetjmqKhF/Invoicing-copy, code I used was:
```javascript
<a v-bind:href="'https://example.com/example/?' + new URLSearchParams({invoice: invoice.Number, client: invoice.Client?.Name||''}).toString()">Pay Now</a>
```
(used `URLSearchParams` so there wouldn't be a problem if client name has spaces in it or other special characters).
I think `business` isn't available in the part of the template you're changing.

**Comment by nittygrittytechy** [comment]
Yes, that was the error I was receiving and because I am not familiar with Vue.js, I didn't know how to fix it at that moment. Okay, let me give this a try. Oh my goodness, thank you again for helping me.

Over the top!!! Can I leave a review for you?

**Comment by nittygrittytechy** [comment]
YES!!!!!!!!!!!!!!!! It worked, oh, thank you so much!
Doin a jig, lol!
![image](https://user-images.githubusercontent.com/72896149/165981024-dd2896e1-f444-4886-8c30-91c93604684c.png)
