### ISSUE TITLE
Custom Invoice CSS not showing on Print

### ISSUE THREAD

**Issue by nittygrittytechy** [gristlabs/grist-widget#27]
Hello,

This might be a stupid question, so sorry in advance.

I have added my own css to customize the look, however it is not showing up when I hit the Print button. 

Can you please tell, do I need to add something to the invoice.js file or do you know why the css is not carrying forward?
![image](https://user-images.githubusercontent.com/72896149/166266142-c35f98fd-2dab-46c6-9e3b-5601bf24ce35.png)

The first part should have green and the button has no styling.
![image](https://user-images.githubusercontent.com/72896149/166266329-7c6ed50b-a316-4889-ba07-985f06166b38.png)
![image](https://user-images.githubusercontent.com/72896149/166266400-b5af806e-0b52-4d31-b9b2-03d9490433e5.png)

My CSS
![image](https://user-images.githubusercontent.com/72896149/166266522-e2b45196-2afc-49df-a062-bd1e363262df.png)

Thank you

**Comment by dsagal** [comment]
It might just be an issue with browsers generally being resistant to printing background colors. If you look at other parts of the invoice that set a `background-color`, I see also another property: `color-adjust: exact !important`. Try using that for your styles too -- it seems [relevant to printing](https://css-tricks.com/almanac/properties/c/color-adjust/#aa-printed-styles).

**Comment by nittygrittytechy** [comment]
Okay, thank you. I will give that a try :)

**Comment by nittygrittytechy** [comment]
Well, that didn't work for me, hmmmm
`.buttonELF {
  background-color: #4CAF50; /* Green */
  border: none;
  color: #ffffff;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
  color-adjust: exact !important;}
.buttonELF a {color:#ffffff;text-decoration: none;color-adjust: exact !important;}
.buttonELF:hover{background-color:#f1f1f1;color-adjust: exact !important;}
.buttonELF a:hover{color:#353535;text-decoration: none;color-adjust: exact !important;}`

`.ServiceCharge{margin:0 right; text-align:right;background-color:#EAF9EE;padding:10px;color-adjust: exact !important;}`

I even checked this on several computers with different browsers. Any ideas?

**Comment by nittygrittytechy** [comment]
Okay I got the button to work, so let me fix the other :)

**Comment by nittygrittytechy** [comment]
Okay I got it, you have to use background. No background-color :)

**Comment by dsagal** [comment]
Thanks for sharing! For anyone else looking at it, I should've mentioned you need both of these (to work across browsers):
```
-webkit-print-color-adjust: exact !important;
color-adjust: exact !important;
````
