### ISSUE TITLE
Adjust the Width of Columns on PDF view

### ISSUE THREAD

**Issue by LeavittANDEldredge** [gristlabs/grist-widget#32]
Hello, 

I am trying to adjust the column width on PDF view. It changed within Grist, but not on the PDF.

Can you please help me.

`.DateWidth{width:12%; -webkit-print-color-adjust: exact !important;
  color-adjust: exact !important;}
.BilledWidth{width:17%; -webkit-print-color-adjust: exact !important;
  color-adjust: exact !important;}`

` <tr>
              <th class="DateWidth">Date</th>
              <th>Service</th>
              <th>Description</th>
              <th class="BilledWidth">Billed By</th>
              <th class="money">Rate</th>
              <th class="number">Qty</th>
              <th class="money">Amount</th>
            </tr>`

![image](https://user-images.githubusercontent.com/105796586/172630525-f8d873eb-d7ca-4451-a57e-8fc153202c71.png)

![image](https://user-images.githubusercontent.com/105796586/172630862-fb290f30-5ded-4a4d-9e44-14fdadae609a.png)

**Comment by berhalak** [comment]
Hi,

You can try to use this  `white-space: nowrap;` CSS property. For example:

`
.DateWidth{width:12%; -webkit-print-color-adjust: exact !important; color-adjust: exact !important; white-space: nowrap;}
`
And use this class on all td elements that have dates (not only on the header). Similar thing can be done for other columns.

Document width is different when printed, so it is hard to use relative width units (like %).

**Comment by LeavittANDEldredge** [comment]
Okay, let me try that, thank you.

**Comment by LeavittANDEldredge** [comment]
Awesome, thank you so much.



*Jennifer Bledsoe*
Graphic Designer/I.T. Tech
Phone: 844-728-3680
Email: ***@***.***
Website: www.uslawpros.com
4204 S.W. Green Oaks Blvd. Suite #140 Arlington, TX 76017
<https://www.facebook.com/eldredgelawfirmarlington>
<https://twitter.com/EldredgeLaw>
<https://www.linkedin.com/company/eldredge-law-firm/>

*The information contained in this e-mail and any attached documents may be
privileged, confidential and protected from disclosure. If you are not the
intended recipient you may not read, copy, distribute or use this
information. If you have received this communication in error, please
notify the sender immediately by replying to this message and then delete
it from your system.*

*Please note the "Eldredge Law Firm" is now called the "Leavitt & Eldredge
Law Firm."*

**Comment by LeavittANDEldredge** [comment]
Thank you, that worked out!
